### ISSUE TITLE
Periods in transform names end the name during export

### ISSUE THREAD

**Issue by linuxgurugamer** [taniwha/io_object_mu#22] opened 2019-09-18 01:31 UTC
Ran into this while renaming an object to one of the following:

AtlasMotor1.25     was saved as:  AtlasMotor1
AtlasMotor1.875   was saved as:  AtlasMotor1
AtlasMotor2.5   was saved as:  AtlasMotor2

**Comment by taniwha** [comment] 2019-12-22 11:32
the 1.25 and 2.5 can be checked easily, but 1.875 is a problem. All because blender uses 3 digits for its duplicate name fixup.

**Comment by taniwha** [comment] 2020-04-30 03:50
I just checked an the exporter leaves 1.25 and 2.5 alone, but does indeed remove the 875 (by design, as it matches blender's handling of duplicate objects).
If the 25 and 5 got stripped from the others, that is something else: the exporter strips only 3 digit extensions, and does not alter the names of existing objects.

**Comment by taniwha** [comment] 2020-04-30 03:50
oops, didn't mean to close it just yet

**Comment by taniwha** [comment] 2024-06-19 14:48
I've taken care of this by adding a special separator (∧ utf 2227): if present it overrides the check for periods. It's added on import and shouldn't be too hard to add on one-off parts manually when needed to protect transform names. However, it's optional as adding it to every object in the blend file would take far too long, so the old behavior is still there if there is no ∧ in the name. Also, only the last ∧ is stripped.

**Closed** 2024-06-19 14:49 UTC
